const PatientDetailSchema = {
    name: 'patientDetailData',
    properties: {
      _id: 'objectId',
      address: 'string?', 
      adherence: 'int?',
      age: 'int?', 
      alertsId: 'string?', 
      bloodGroup: 'string?', 
      bmi: 'string?',
      carePlanId: 'string?',
      currentlyUnwell: 'string?',
      doctorReqDataId: 'string?',
      email: 'string?',
      entryBy: 'string?',
      entryById: 'string?',
      entryDate: 'string?',
      entryStatus: 'string?',
      gender: 'string?',
      height: 'int?',
      img: 'string?',
      languages: 'string[]',
      lastUpdated: 'string?',
      location: 'string?',
      memberType: 'string?',
      nextOfKinEmail: 'string?',
      nextOfKinFullName: 'string?',
      nextOfKinPhoneNumber: 'string?',
      patientId: 'string?',
      patientMHId: 'string?',
      patientName: 'string?',
      phoneNumber: 'string?',
      realm_id: 'string?',
      recoveryStatus: 'string?',
      remaindersId: 'string?',
      symptomCatId: 'string?',
      watchClosely: 'string?',
      weight: 'int?',
      ethincity: 'string?',
      hmcigrattes: 'string?',
      hmdrinks: 'string?',
      hmhoursWRC: 'string?',
      occupation: 'string?'
      },
    primaryKey: '_id',
  };

 export default PatientDetailSchema;
